- package.json
To test, cannot build it on my computer.
> Tried to build 32 bits version

- package.json
- yarn.lock
Some dependency is broken for the current webpack version, so I updated it.
> Updated webpack version

- .gitlab-ci.yml
Envoies les liens de download des releases sur la PR GitHub
Visiblement la version linux n'est pas buildée :/
reste à faire: pb des numéros de version en dur
> feat: post artifacts to GitHub PR

- .eslintrc.js
- package.json
- src/exporters/audit/audit-report-exporter.ts
- src/exporters/audit/audit-report-values-computer.test.ts
- src/exporters/audit/audit-report-values-computer.ts
- src/reducers/files-and-folders/files-and-folders-selectors.ts
- src/util/functionnal-programming-utils.ts
- yarn.lock
Depends on https://github.com/SocialGouv/archifiltre/pull/241
> feat(audit): add data for first audit report page

- src/components/header/a-new-version-is-available.js
- src/reducers/store-thunks.ts
- src/translations/en.json
- src/translations/fr.json
Coucou c'est Chloé! J'ai codé!!! <3
> feat(json): add notification with old json version

- src/components/buttons/load-previous-session-button.tsx
- src/components/folder-dropzone/folder-dropzone-container.tsx
- src/components/header/dashboard/dashboard-container.tsx
- src/components/header/dashboard/dashboard.js
- src/reducers/middleware/persist-actions-middleware.ts
- src/reducers/store-thunks.ts
- src/reducers/store.ts
- src/translations/en.json
- src/translations/fr.json
depends on https://github.com/SocialGouv/archifiltre/pull/425
> feat: allow user to reload his previous session

- src/files-and-folders-loader/files-and-folders-loader.test.ts
- src/files-and-folders-loader/files-and-folders-loader.ts
- src/load-from-filesystem.fork.js
- src/reducers/store-thunks.ts
Depends on https://github.com/SocialGouv/archifiltre/pull/445
> refactor: refactor filesAndFolders and metadata computing

- src/exporters/resip/resip-exporter.test.ts
Make the resip-exporter.test work on the Windows platform
> fix(test): make test work on Windows

- renovate.json
> chore(renovate): use our SocialGouv/renovate-config

- src/components/modals/search-modal/filters/size-filter.tsx
> fix(units): fix units in search filters

- README.md
- package.json
- scripts/translation-csv-to-json.js
Depends on https://github.com/SocialGouv/archifiltre/pull/914
> chore: add a script to import a translation csv to the JSON translation files

- src/files-and-folders-loader/file-system-loading-process-utils.ts
- src/files-and-folders-loader/files-and-folders-loader-types.ts
- src/files-and-folders-loader/files-and-folders-loader.test.ts
- src/files-and-folders-loader/files-and-folders-loader.ts
- src/reducers/files-and-folders/files-and-folders-actions.ts
- src/reducers/files-and-folders/files-and-folders-reducer.test.ts
- src/reducers/files-and-folders/files-and-folders-reducer.ts
- src/reducers/files-and-folders/files-and-folders-selectors.ts
- src/reducers/files-and-folders/files-and-folders-types.ts
- src/reducers/store-thunks.ts
depends on https://github.com/SocialGouv/archifiltre/pull/1007
> fix: fix moved files not being clickable after json reload

- src/components/modals/export-modal/export-config.ts
> fix: fix waiting for hashes message not appearing on disabled excel export

- .github/workflows/ci.yml
- .releaserc.yml
- CHANGELOG.md
- package.json
--- 
versions
---
Closes #1095 
Closes #1010
Closes #1121
> feat(github): allow manual build trigged on github

- README.md
> docs(README): add badges

- .github/workflows/ci.yml
> ci(github): update to actions/setup-node@v2

- .eslintrc.js
- src/hash-computer/hash-computer-thunk.ts
> fix(hash): fix windows specific file hash with correct path

- src/renderer/components/main-space/workspace/enrichment/tags/all-tags.tsx
Closes #1465 
Restaurer l'affichage de la bibliothèque de tags
> fix(tags): fix tags library not being displayed

- electron/build/installer.nsh
- package.json
- scripts/replaceForChannel.js
> fix(release): change default windows install path

- src/renderer/utils/array-export/array-export.ts
Closes #1477
Corriger la disparition de la colonne à éliminer dans les exports.
> fix(exports): fix elements to delete not appearing in exports

- .github/workflows/release.yml
> fix(release): fix release version management

- package.json
- src/renderer/components/modals/modal-header.tsx
- src/renderer/components/modals/settings-modal/settings-modal.tsx
- src/renderer/exporters/audit/audit-report-exporter.ts
- src/renderer/exporters/csv/csv-exporter.ts
- src/renderer/exporters/csv/tree-csv-exporter.ts
- src/renderer/exporters/deletion-script/deletion-script-exporter.ts
- src/renderer/exporters/excel/excel-exporter.ts
- src/renderer/exporters/resip/resip-exporter-thunk.ts
- src/renderer/translations/en.json
- src/renderer/translations/fr.json
- src/renderer/utils/export.ts
- src/renderer/utils/notifications.ts
- tests/e2e/audit-export.test.ts
- tests/e2e/csv-export.test.ts
- tests/e2e/csv-with-hashes-export.test.ts
- tests/e2e/deletion-script-export.test.ts
- tests/e2e/excel-export.test.ts
- tests/e2e/resip-export.test.ts
- tests/e2e/tree-csv-export.test.ts
- tests/e2e/utils/app.ts
> fix: fix language impact on e2e tests

- src/renderer/translations/de.json
Closes #x
Il manque plusieurs lignes dans la traduction allemande.
> feat: Added missing translation

- package.json
- src/renderer/components/common/version.tsx
- src/renderer/components/header/header.tsx
- src/renderer/components/start-screen/start-screen.tsx
- src/renderer/version.ts
Ajouter versions dans les différents écrans principaux.
> feat(version): add app version in main views

- publiccode.yml
Closes #1645 
Pouvoir être visible des recherches publicode
> feat: Create publiccode.yml file

- README.md
> fix: added codegouv badge to the readme

- src/common/utils/queue/queue.ts
- src/renderer/components/background-loading-info/background-loading-info.tsx
- src/renderer/hash-computer/hash-computer-thunk.ts
- src/renderer/reducers/loading-info/loading-info-actions.ts
**Ce correctif résout le problème de la progression du calcul des empreintes − qui parfois − n’allait pas à 100 %.** Le bug identifié était une erreur [off-by-one](https://fr.wikipedia.org/wiki/Erreur_off-by-one) qui empêchait la barre de progression d’atteindre les 100 %.
> fix: progress completion on hashes calculation to 100%

- publiccode.yml
> chore: add "fundedBy" to publiccode.yml

- package.json
- src/renderer/constants.ts
> chore: update website url

- src/renderer/utils/array-export/array-export.ts
- src/renderer/utils/duplicates.ts
- src/renderer/utils/export.ts
> fix: intermittent csv export with hashes bug

- package.json
- src/renderer/version.ts
Indication du nom et du numéro de la version 4.2.0
> chore: update version
